export const MOCK_ATHLETES = [
  { 
    id: "860642", 
    firstName: "გიორგი", 
    lastName: "ბერიძე", 
    personalId: "01010101010", 
    status: "აქტიური", 
    memberSince: "15/01/2023", 
    height: "180", 
    weight: "75", 
    bloodType: "O+", 
    phone: "+995555123456", 
    email: "g.beridze@example.com", 
    level: 3, 
    referral: 101, 
    photo: "https://i.pravatar.cc/150?img=11",
    birthDate: "2000-05-15",
    nationality: "GE",
    asthma: false,
    diabetes: false,
    allergies: "არ აქვს",
    emergencyContactName: "ნიკოლოზ ბერიძე",
    emergencyContactRelation: "მამა",
    emergencyContactPhone: "+995555778899",
    isFederationMember: true,
    membershipStatus: "Active",
    membershipFeePaid: true,
    isFounder: false,
    hasVotingRight: true,
    isNationalTeamMember: true,
    isVeteran: false,
    isMentor: true,
    sportsDiscipline: "ალპინიზმი",
    isClubMember: true,
    clubId: "3",
    achievements: [
      { year: 2025, peak: "ევერესტი", route: "სამხრეთ ქედი", result: "ჟანგბადის გარეშე" },
      { year: 2024, peak: "უშბა", route: "სარკის მარშრუტი", result: "ოქროს ყინულცული" }
    ],
    biography: "გიორგი ბერიძე არის გამოცდილი ალპინისტი, რომელმაც არაერთ მწვერვალზე განახორციელა წარმატებული ასვლა."
  },
  { 
    id: "860643", 
    firstName: "დავით", 
    lastName: "მაისურაძე", 
    personalId: "02020202020", 
    status: "აქტიური", 
    memberSince: "10/02/2023", 
    height: "185", 
    weight: "80", 
    bloodType: "A+", 
    phone: "+995555654321", 
    email: "d.maisuradze@example.com", 
    level: 2, 
    referral: 85, 
    photo: "https://i.pravatar.cc/150?img=12",
    birthDate: "2009-10-12",
    nationality: "GE",
    asthma: true,
    diabetes: false,
    allergies: "თხილის ალერგია",
    emergencyContactName: "ეკატერინე მაისურაძე",
    emergencyContactRelation: "დედა",
    emergencyContactPhone: "+995555112233",
    representativeType: "parent",
    representativeName: "ეკატერინე მაისურაძე",
    representativePersonalId: "01020304050",
    representativePhone: "+995555112233",
    representativeDoc: { name: "დაბადების_მოწმობა.pdf", size: 1204500, type: "application/pdf", data: "#" },
    isFederationMember: true,
    membershipStatus: "Active",
    membershipFeePaid: true,
    isFounder: false,
    hasVotingRight: false,
    isNationalTeamMember: false,
    isVeteran: false,
    isMentor: false,
    sportsDiscipline: "მეკლდეურობა",
    isClubMember: false,
    clubId: null,
    achievements: [],
    biography: ""
  },
  { 
    id: "860644", 
    firstName: "ნიკოლოზ", 
    lastName: "ლომიძე", 
    personalId: "03030303030", 
    status: "აქტიური", 
    memberSince: "05/03/2024", 
    height: "176", 
    weight: "68", 
    bloodType: "B+", 
    phone: "+995555987654", 
    email: "n.lomidze@example.com", 
    level: 3, 
    referral: 92, 
    photo: "https://i.pravatar.cc/150?img=13",
    birthDate: "1998-04-20",
    nationality: "GE",
    asthma: true,
    diabetes: false,
    allergies: "არ აქვს",
    emergencyContactName: "ირაკლი ლომიძე",
    emergencyContactRelation: "ძმა",
    emergencyContactPhone: "+995555223344",
    isFederationMember: true,
    membershipStatus: "Active",
    membershipFeePaid: true,
    isFounder: false,
    hasVotingRight: true,
    isNationalTeamMember: false,
    isVeteran: false,
    isMentor: false,
    sportsDiscipline: "მეკლდეურობა",
    isClubMember: true,
    clubId: "3",
    achievements: [
      { year: 2025, peak: "კატეგორია 7b+ მარშრუტი", route: "ჭიათურის კანიონი", result: "წარმატებული ფლეში" }
    ],
    biography: "ნიკოლოზ ლომიძე არის პროფესიონალი მეკლდეური, თბილისის ალპური კლუბის წევრი და აქტიური სპორტსმენი."
  }
];

export const MOCK_CLUBS = [
  { id: 1, name: "მთამსვლელთა კლუბი 'თეთნულდი'", status: "ააიპ", regNo: "400123456", date: "2015-05-10", members: 120, region: "სამეგრელო-ზემო სვანეთი", lat: 43.0333, lng: 42.7333, managerName: "ზურაბ მარგიანი", managerId: "01010101010", managerPhone: "+995555123456", managerEmail: "zurab@example.com" },
  { id: 2, name: "თბილისის სათავგადასავლო კლუბი", status: "შპს", regNo: "200987654", date: "2018-08-20", members: 350, region: "თბილისი", lat: 41.7151, lng: 44.8271, managerName: "გიორგი ნემსაძე", managerId: "01010101011", managerPhone: "+995555654321", managerEmail: "giorgi@example.com" },
  { id: 3, name: "თბილისის ალპური კლუბი", status: "ააიპ", regNo: "401928374", date: "2012-03-15", members: 95, region: "თბილისი", lat: 41.7151, lng: 44.8271, managerName: "ლევან კოხრეიძე", managerId: "01020304051", managerPhone: "+995555456789", managerEmail: "levan@example.com" }
];

export const MOCK_INCIDENTS = [
  { id: "1", athleteId: "860642", date: "2026-05-15", time: "10:30", location: "ცენტრალური მოედანი", severity: "მაღალი", description: "მძიმე ტრავმა", status: "მიმდინარე", attachments: [] }
];
